export const ACTIONS = {
  INIT_CONTAINER: 'CHAT__INIT_CONTAINER',
  EXIT_CONTAINER: 'CHAT__EXIT_CONTAINER',
  CHAT_CONNECT: 'CHAT__CONNECT',
  CHAT_DISCONNECT: 'CHAT__DISCONNECT',
  SUBMIT_MESSAGE: 'CHAT__SUBMIT_MESSAGE',
  SEND_MESSAGE: 'CHAT__SEND_MESSAGE',
  SEND_MESSAGE_SUCCESS: 'CHAT__SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_ERROR: 'CHAT__SEND_MESSAGE_ERROR',
  UPDATE_MESSAGES: 'CHAT__UPDATE_MESSAGES',
};