export const ACTIONS = {
  SIGN_IN: 'LOGIN__SIGN_IN',
  SIGN_IN_SUCCESS: 'LOGIN__SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'LOGIN__SIGN_IN_ERROR',
  SIGN_OFF: 'LOGIN__SIGN_OFF',
  SIGN_OFF_SUCCESS: 'LOGIN__SIGN_OFF_SUCCESS',
  SIGN_OFF_ERROR: 'LOGIN__SIGN_OFF_ERROR',
  VALIDATE_USERNAME: 'LOGIN__VALIDATE_USERNAME',
};